version: '3.7'

networks:
 proxy-net:
   external: true
   
volumes:
  PRMS_mariadb10:
  PRMS_liam3_mariadb10:
  PRMS_liam3_server:
  PRMS_liam3_client:
  PRMS_server:

services:

  PRMS_mariadb10:
    image: mariadb:10.4.8
    hostname: PRMS_mariadb10
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - PRMS_mariadb10:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
    networks:
      - proxy-net 

  PRMS_liam3_mariadb10:
    image: mariadb:10.4.8
    hostname: PRMS_liam3_mariadb10
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - PRMS_liam3_mariadb10:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
    networks:
      - proxy-net 

  PRMS_phpmyadmin-mariadb:
    image: phpmyadmin/phpmyadmin:4.8.5
    hostname: PRMS_phpmyadmin_mariadb10
    depends_on:
    - PRMS_mariadb10
    environment:
    - PMA_HOST=PRMS_mariadb10
    - PMA_PORT=3306
    - PMA_USER=test
    - PMA_PASSWORD=test
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.PRMS_phpmyadmin-mariadb.rule=Host(`PRMS_phpmyadmin_mariadb10.bpmspace.net`)
        - traefik.http.services.PRMS_phpmyadmin-mariadb-service.loadbalancer.server.port=80
    networks:
      - proxy-net 

  PRMS_liam3_phpmyadmin-mariadb:
    image: phpmyadmin/phpmyadmin:4.8.5
    hostname: PRMS_liam3_phpmyadmin_mariadb10
    depends_on:
    - PRMS_liam3_mariadb10
    environment:
    - PMA_HOST=PRMS_liam3_mariadb10
    - PMA_PORT=3306
    - PMA_USER=test
    - PMA_PASSWORD=test
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.PRMS_liam3_phpmyadmin-mariadb.rule=Host(`PRMS_liam3_phpmyadmin_mariadb10.bpmspace.net`)
        - traefik.http.services.PRMS_liam3_phpmyadmin-mariadb-service.loadbalancer.server.port=80
    networks:
      - proxy-net
      
  PRMS_liam3_server:
    image: bpmspace/liam3:liam3_master-production_server_master
    hostname: PRMS_liam3_server
    volumes:
    - PRMS_liam3_server:/var/www/html
    depends_on:
    - PRMS_liam3_mariadb10
    environment:
    - DB_HOST=PRMS_liam3_mariadb10
    - DB_PORT=3306
    - DB_USER=test
    - DB_PASSWORD=test
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.PRMS_liam3_server.rule=Host(`PRMS_liam3_server.bpmspace.net`)
        - traefik.http.services.PRMS_liam3_server-service.loadbalancer.server.port=80
    networks:
      - proxy-net

  PRMS_liam3_client:
    image: bpmspace/liam3:liam3_client_master-production_server_master
    hostname: PRMS_liam3_client
    volumes:
    - PRMS_liam3_client:/var/www/html
    depends_on:
    - PRMS_liam3_server
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.PRMS_liam3_client.rule=Host(`PRMS_liam3_client.bpmspace.net`)
        - traefik.http.services.PRMS_liam3_client-service.loadbalancer.server.port=80
    networks:
      - proxy-net

  PRMS_server:
    image: bpmspace/prms:dev_development_server_master
    hostname: PRMS_server
    volumes:
    - PRMS_liam3_server:/var/www/html
    depends_on:
    - PRMS_mariadb10
    environment:
    - DB_HOST=PRMS_mariadb10
    - DB_PORT=3306
    - DB_USER=test
    - DB_PASSWORD=test
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.PRMS_server.rule=Host(`PRMS_server.bpmspace.net`)
        - traefik.http.services.PRMS_server-service.loadbalancer.server.port=80
    networks:
      - proxy-net
